
    create table banner (
        id bigint generated by default as identity,
        primary key (id)
    );

    create table banner_urls (
        banner_id bigint not null,
        url varchar(255)
    );

    create table cart_items (
        discounted_price numeric(38,2),
        price numeric(38,2) not null,
        quantity integer not null,
        cart_id bigint,
        id bigint generated by default as identity,
        product_id bigint,
        primary key (id)
    );

    create table carts (
        discount numeric(38,2),
        total_discount_price numeric(38,2),
        total_item integer,
        total_price numeric(38,2),
        coupon_id bigint,
        id bigint generated by default as identity,
        user_id bigint not null unique,
        primary key (id)
    );

    create table collections (
        active boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        description_line_one varchar(255),
        description_line_two varchar(255),
        headline_title varchar(255),
        name varchar(255),
        slug varchar(255),
        primary key (id)
    );

    create table contact_info (
        created_at timestamp(6),
        id bigint generated by default as identity,
        user_id bigint,
        cel varchar(255),
        document_type varchar(255) check (document_type in ('DNI','CE')),
        email varchar(255),
        full_name varchar(255),
        identity_document varchar(255),
        primary key (id)
    );

    create table coupon (
        active boolean not null,
        discount_percentage integer,
        expiry_date timestamp(6),
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table email_verification (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        code varchar(255) not null,
        email varchar(255) not null unique,
        primary key (id)
    );

    create table order_items (
        discount_price numeric(38,2),
        price numeric(38,2),
        quantity integer not null,
        delivery_date_time timestamp(6),
        id bigint generated by default as identity,
        order_id bigint,
        product_id bigint,
        user_id bigint,
        primary key (id)
    );

    create table orders (
        coupon_discount numeric(38,2),
        total_discounted_price numeric(38,2),
        total_items integer not null,
        total_price numeric(38,2),
        contact_info_id bigint unique,
        created_at timestamp(6),
        delivery_date_time timestamp(6),
        id bigint generated by default as identity,
        payment_id bigint,
        shipping_address_id bigint unique,
        user_id bigint,
        coupon_code varchar(255),
        external_reference varchar(255),
        invoice_url varchar(255),
        order_id varchar(255),
        order_status varchar(255) check (order_status in ('CREATED','PENDING_PAYMENT','PAID','PROCESSING','SHIPPED','DELIVERED','CANCELLED','REFUNDED','FAILED')),
        payer_email varchar(255),
        payment_method varchar(255),
        payment_type varchar(255),
        status varchar(255),
        transaction_amount varchar(255),
        primary key (id)
    );

    create table password_reset_token (
        used boolean not null,
        created_at timestamp(6),
        expires_at timestamp(6),
        id bigint generated by default as identity,
        email varchar(255),
        token varchar(255),
        primary key (id)
    );

    create table payment_information (
        expiration_date timestamp(6),
        user_id bigint not null,
        card_holder_name varchar(255),
        card_number varchar(255),
        cvv varchar(255)
    );

    create table product_images (
        product_id bigint not null,
        image_url varchar(255)
    );

    create table products (
        active boolean,
        discount_percentage integer,
        price numeric(38,2),
        quantity integer,
        collection_id bigint,
        created_at timestamp(6),
        discount_until timestamp(6),
        id bigint generated by default as identity,
        color varchar(255),
        description varchar(255),
        description_archetype varchar(255),
        material varchar(255),
        slug varchar(255),
        title varchar(255),
        primary key (id)
    );

    create table shipping_address (
        id bigint generated by default as identity,
        user_id bigint,
        additional_info varchar(255),
        apartment_or_floor varchar(255),
        department varchar(255),
        district varchar(255),
        full_address varchar(255),
        province varchar(255),
        reference varchar(255),
        primary key (id)
    );

    create table users (
        created_at timestamp(6),
        id bigint generated by default as identity,
        cel varchar(255),
        email varchar(255),
        identity_document varchar(255),
        name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ADMIN','CLIENT')),
        status varchar(255) check (status in ('ACTIVE','INACTIVE')),
        primary key (id)
    );

    alter table if exists banner_urls 
       add constraint FK172uxohnbgk35fimickkq0eas 
       foreign key (banner_id) 
       references banner;

    alter table if exists cart_items 
       add constraint FKpcttvuq4mxppo8sxggjtn5i2c 
       foreign key (cart_id) 
       references carts;

    alter table if exists cart_items 
       add constraint FK1re40cjegsfvw58xrkdp6bac6 
       foreign key (product_id) 
       references products;

    alter table if exists carts 
       add constraint FKpfuo0frlisvfiye36338io4um 
       foreign key (coupon_id) 
       references coupon;

    alter table if exists carts 
       add constraint FKb5o626f86h46m4s7ms6ginnop 
       foreign key (user_id) 
       references users;

    alter table if exists contact_info 
       add constraint FK8b9r676lain0grbn1jacg4t26 
       foreign key (user_id) 
       references users;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FKli3ua5uggpx5jjoer07pan8bg 
       foreign key (contact_info_id) 
       references contact_info;

    alter table if exists orders 
       add constraint FK2dntnxe9677sy06ujhix6o2bp 
       foreign key (shipping_address_id) 
       references shipping_address;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists payment_information 
       add constraint FK5xb28hck1puvn9ldjnbb1vqm8 
       foreign key (user_id) 
       references users;

    alter table if exists product_images 
       add constraint FKqnq71xsohugpqwf3c9gxmsuy 
       foreign key (product_id) 
       references products;

    alter table if exists products 
       add constraint FKa3uk0ig3pw6efw9b0dmoh733q 
       foreign key (collection_id) 
       references collections;

    alter table if exists shipping_address 
       add constraint FKilmh1is3sdv0h8xdsrh0yn5f3 
       foreign key (user_id) 
       references users;
